"""Legacy LOS CSV conversion.

Phase 1 reads, validates, and maps an extract into an immutable :class:`ConversionPlan`.
Phase 2 loads that plan, unchanged, into a new isolated database (:func:`load_plan`).
Phase 3 reconciles the loaded database independently against the archived source
(:func:`reconcile_run`). The contract is docs/conversion-specification.md. Release approval is
not implemented yet.
"""

from loan_lab.conversion.legacy.contract import SOURCE_SYSTEM, Rule
from loan_lab.conversion.legacy.loader import (
    LoadCounts,
    LoadFailedError,
    LoadResult,
    TargetPreconditionError,
    load_plan,
    new_run_id,
)
from loan_lab.conversion.legacy.plan import (
    AmountTotals,
    ApplicationUnit,
    Cause,
    ConversionPlan,
    Disposition,
    Issue,
    MappedApplication,
    MappedBorrower,
    MappedParty,
    Outcome,
    RowResult,
    UnmappedField,
)
from loan_lab.conversion.legacy.planner import build_plan, plan_conversion
from loan_lab.conversion.legacy.reconcile import (
    Discrepancy,
    ReconciliationCheck,
    ReconciliationConflictError,
    ReconciliationNotFinalizedError,
    ReconciliationRefusedError,
    ReconciliationResult,
    ReconciliationRule,
    RuleResult,
    reconcile_run,
    verify_reconciliation,
)
from loan_lab.conversion.legacy.reports import ReportKind, ReportState, build_reports
from loan_lab.conversion.legacy.run import (
    ArchivedSource,
    DatabaseState,
    EvidenceIncompleteError,
    EvidenceState,
    EvidenceUnreadableError,
    LoadRun,
    LoadRunFailedError,
    Readiness,
    ReconciliationState,
    RecoveryResult,
    ReportRunFailedError,
    RunFailedError,
    RunStatus,
    SourceChangedError,
    SourceRunFailedError,
    TransactionState,
    check_ready,
    fail_run,
    recover_run,
    run_conversion,
    run_load,
)
from loan_lab.conversion.legacy.source import (
    ControlTotals,
    RunIssue,
    SourceExtract,
    SourceRef,
    SourceValidationError,
    read_extract,
)

__all__ = [
    "SOURCE_SYSTEM",
    "AmountTotals",
    "ApplicationUnit",
    "ArchivedSource",
    "Cause",
    "ControlTotals",
    "ConversionPlan",
    "DatabaseState",
    "Discrepancy",
    "Disposition",
    "EvidenceIncompleteError",
    "EvidenceState",
    "EvidenceUnreadableError",
    "Issue",
    "LoadCounts",
    "LoadFailedError",
    "LoadResult",
    "LoadRun",
    "LoadRunFailedError",
    "MappedApplication",
    "MappedBorrower",
    "MappedParty",
    "Outcome",
    "RowResult",
    "Rule",
    "Readiness",
    "ReconciliationCheck",
    "ReconciliationConflictError",
    "ReconciliationNotFinalizedError",
    "ReconciliationRefusedError",
    "ReconciliationResult",
    "ReconciliationRule",
    "ReconciliationState",
    "RecoveryResult",
    "ReportKind",
    "ReportRunFailedError",
    "ReportState",
    "RuleResult",
    "RunFailedError",
    "RunIssue",
    "RunStatus",
    "SourceChangedError",
    "SourceRunFailedError",
    "SourceExtract",
    "SourceRef",
    "SourceValidationError",
    "TargetPreconditionError",
    "TransactionState",
    "UnmappedField",
    "build_plan",
    "build_reports",
    "check_ready",
    "fail_run",
    "load_plan",
    "new_run_id",
    "plan_conversion",
    "read_extract",
    "reconcile_run",
    "recover_run",
    "run_conversion",
    "run_load",
    "verify_reconciliation",
]
